/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {

}

export type webhooks = Record<string, never>;

export interface components {

}

export type external = Record<string, never>;

export interface operations {

}
